from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from src.storage.database import Base


class User(Base):
    """
    Stores basic information about Telegram users who interact with the bot.
    """

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    # Telegram user IDs exceed 32-bit signed int; Postgres INTEGER overflows (see Fly logs).
    telegram_id = Column(BigInteger, unique=True, nullable=False, index=True)
    username = Column(String(255), nullable=True)
    first_seen_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)

    # Relationship to preferences
    preference = relationship("UserPreference", back_populates="user", uselist=False)


class UserPreference(Base):
    """
    Stores user preferences for news filtering and delivery frequency.
    """

    __tablename__ = "user_preferences"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), unique=True, nullable=False)
    # Categories: comma-separated lowercase tokens matched against NewsArticle.category
    # (same taxonomy as _extract_category / bot labels), e.g. sports, politics, tourism.
    # Empty means all. Token "sarawak" also matches state=sarawak, label Local, or text "sarawak".
    categories = Column(String(500), nullable=True, default="")
    # Locations: comma-separated list like "kuching,miri,sibu" or empty for all Sarawak
    locations = Column(String(500), nullable=True, default="")
    # Area keywords: comma-separated free-text phrases like "jalan wawasan,taman desa,bekalan air"
    # For Telegram channel posts: if set, a user only receives posts whose text matches one of these phrases.
    # For RSS/other: used with geo ranking (priority), not as a hard filter unless noted in services.
    area_keywords = Column(String(1000), nullable=True, default="")
    # Frequency values:
    # - every_15m, every_30m, every_1h, every_3h, every_6h, every_12h
    # Legacy values (instant/daily) are still accepted in runtime mapping.
    frequency = Column(String(50), nullable=False, default="every_1h")
    wants_urgent_alerts = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationship to user
    user = relationship("User", back_populates="preference")


class NewsArticle(Base):
    """
    Stores basic information about a news article.
    Duplicate prevention is based on the unique 'link' field.
    """

    __tablename__ = "news_articles"
    __table_args__ = (
        UniqueConstraint("link", name="uq_news_link"),
    )

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(500), nullable=False)
    link = Column(String(1000), nullable=False)
    source = Column(String(255), nullable=False)
    raw_summary = Column(Text, nullable=True)  # from RSS feed, optional
    ai_summary = Column(Text, nullable=True)  # generated by local LLM, cached
    # Taxonomy label for user /settings category matching (same strings as _extract_category / LLM tags).
    category = Column(String(64), nullable=True)
    # Coarse location/state extracted from the headline for better prioritization.
    # If state == "sarawak", location will be one of the canonical Sarawak city/region keys.
    # Otherwise location can be NULL and state will be "other".
    location = Column(String(255), nullable=True)
    state = Column(String(20), nullable=True)  # "sarawak" or "other"
    # Deprecated: was used for global “already sent” dedup (wrong for multi-user).
    # Per-user delivery is tracked in UserArticleDelivery. Kept for DB compatibility.
    last_sent_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class UserArticleDelivery(Base):
    """
    Records that a given user has been shown a given article (scheduled push / /latest dedup).
    Replaces the global NewsArticle.last_sent_at anti-pattern for multi-tenant bots.
    """

    __tablename__ = "user_article_delivery"
    __table_args__ = (
        UniqueConstraint("user_id", "article_id", name="uq_user_article_delivery"),
    )

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    article_id = Column(Integer, ForeignKey("news_articles.id"), nullable=False, index=True)
    sent_at = Column(DateTime, default=datetime.utcnow, nullable=False)

